### ISSUE TITLE
Cheastshop Update

### ISSUE THREAD

**Issue by ExticDev** [Creeperface01/ChestShop#3]
Hey,
When do you update your plugin? It's going to be a problem right now.
2019-07-19 23:23:44.445 [main] FATAL - Das Event "cn.nukkit.event.inventory.InventoryMoveItemEvent" konnte nicht zu "ChestShop v1.0": null in Zeile com.creeperface.nukkitx.chestshop.ChestShop weitergegeben werden
2019-07-19 23:23:44.445 [main] ERROR - Throwing
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.blockentity.BlockEntityHopper.pickupItems(BlockEntityHopper.java:280) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.blockentity.BlockEntityHopper.onUpdate(BlockEntityHopper.java:167) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.level.Level.lambda$doTick$1(Level.java:792) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at java.util.Collection.removeIf(Collection.java:414) [?:1.8.0_212]
	at cn.nukkit.level.Level.doTick(Level.java:792) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.checkTickUpdates(Server.java:1053) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.tick(Server.java:1134) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:903) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.start(Server.java:880) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.<init>(Server.java:565) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.IllegalStateException: from must not be null
	at com.creeperface.nukkitx.chestshop.ChestShop.onItemMove(ChestShop.kt:407) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor218.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit-1.0-SNAPSHOT.jar:?]
	... 13 more

here the error.

LG F

**Comment by DueKay** [comment]
Ich bekomme leider den selben Fehler angezeigt. Wollte es eben selbst reporten, aber warum sollte ich es doppelt eröffnen :)

Ich hoffe sie können da was tun und das Problem beheben

Lg DueKay

_____________________________________________________________



Unfortunately, I get the same error. I just wanted to report it myself, but why should I open it twice :)

I hope you can do that and fix the problem

Lg DueKay

**Comment by Hajatoby** [comment]
same Problem
